#pragma once

typedef enum 
{
	DENOMINATION = 1,
	CASINO_NUMBER,
	COMM_ID,
	SEN_OPTIONS1,
	SEN_OPTIONS2,
	SLOT_NUMBER,
	PLAYER_PREFIXES,
	OTHER_PREFIXES,
	CASINO_NAME,
	POINTS_PER_DOLLAR,
	LOSS_LIMIT,
	TICKETING,
	PLAYER_TRACKING,
	VIRTUAL_SESSIONS,
	CARD_TIMEOUT,
	FLOOR_LOCK,
	ALLOW_FLOOR_LOCKOUT,
	PBT,
	CASH_TRANSFER_TRACKING,
	TIMEZONE,
	SLOTMAST_REVISION,
	POINTS_FOR_PROMO,
	SEND_FULL_METER_UPDATE,
	UNIVERSE_ENABLED,
	UNIVERSE_PROP_CODES,
	UNIVERSE_PLAYER_PREFIXES,
	FEATURE_FLAGS,
	NCL_ENABLED_CARD_TRACK,
	SHOW_POINTS_VS_ACCOUNT_BALANCE = 29,
	SESSION_POINTS_TEXT = 30,
	POINTS_OR_CASH_LABEL = 31,
	BALANCE_RETRIEVAL_TEXT = 32,
	DAILY_POINTS_DISPLAY_SUFFIX = 33,
	TIER_POINTS_LABEL = 34,
	PLAYER_PROFILE_BUTTON = 35,
	GLOBAL_MGMD_ENABLED = 36,
	EXCESSIVE_VOUCHER_OUT_ENABLED = 37,
	EXCESSIVE_VOUCHER_OUT_THRESHOLD = 38,
	TOTAL_BILL_IN_THRESHOLD = 39,
	COIN_IN_THRESHOLD = 40,
	COIN_OUT_THRESHOLD = 41,
	PARTIAL_WAT_OUT_ENABLED = 42,
	EXTENSIBLE_SYSTEM_SETTINGS = 43,
} FieldTypes;

class CConfigField
{
public:
	CConfigField(void);
	CConfigField(FieldTypes m_type);
public:
	virtual ~CConfigField(void);

	FieldTypes GetType() const
	{
		return m_type;
	}

protected:
	FieldTypes m_type;
};
